# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\generator_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(950, 650)
        Form.setStyleSheet("background-color: rgb(230, 232, 230);")
        self.image = QtWidgets.QLabel(Form)
        self.image.setGeometry(QtCore.QRect(20, 19, 500, 500))
        self.image.setStyleSheet("QLabel\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    font-weight: 500;\n"
"    border-radius: 20px;\n"
"    font-size: 90px;\n"
"    background-color: rgb(230, 232, 230);\n"
"}")
        self.image.setMidLineWidth(2)
        self.image.setScaledContents(False)
        self.image.setWordWrap(False)
        self.image.setObjectName("image")
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setGeometry(QtCore.QRect(540, 20, 400, 500))
        self.listWidget.setStyleSheet("QListWidget\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    border-radius: 20px;\n"
"    padding: 10px;\n"
"}")
        self.listWidget.setAutoScrollMargin(16)
        self.listWidget.setObjectName("listWidget")
        self.add_text_btn = QtWidgets.QPushButton(Form)
        self.add_text_btn.setEnabled(False)
        self.add_text_btn.setGeometry(QtCore.QRect(538, 530, 400, 40))
        self.add_text_btn.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(223, 41, 53);\n"
"    color: white;\n"
"}")
        self.add_text_btn.setObjectName("add_text_btn")
        self.load_btn = QtWidgets.QPushButton(Form)
        self.load_btn.setGeometry(QtCore.QRect(20, 530, 500, 40))
        self.load_btn.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(223, 41, 53);\n"
"    color: white;\n"
"}")
        self.load_btn.setObjectName("load_btn")
        self.export_btn = QtWidgets.QPushButton(Form)
        self.export_btn.setEnabled(False)
        self.export_btn.setGeometry(QtCore.QRect(21, 580, 920, 41))
        self.export_btn.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(223, 41, 53);\n"
"    color: white;\n"
"}")
        self.export_btn.setObjectName("export_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.image.setText(_translate("Form", "Тут \n"
"Будет \n"
"Картинка :)"))
        self.add_text_btn.setText(_translate("Form", "Добавить поле для текста"))
        self.load_btn.setText(_translate("Form", "Загрузить"))
        self.export_btn.setText(_translate("Form", "Экспорт"))
