# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(16)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(230, 232, 230);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 110, 431, 71))
        font = QtGui.QFont()
        font.setFamily("Inter,sans-serif")
        font.setPointSize(30)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: Inter,sans-serif;")
        self.label.setObjectName("label")
        self.open_shablon_list_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_shablon_list_btn.setGeometry(QtCore.QRect(250, 210, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Inter,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.open_shablon_list_btn.setFont(font)
        self.open_shablon_list_btn.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    font-size:25px;\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(223, 41, 53);\n"
"    color: white;\n"
"}")
        self.open_shablon_list_btn.setObjectName("open_shablon_list_btn")
        self.open_own_picture_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_own_picture_btn.setGeometry(QtCore.QRect(250, 300, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Inter,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.open_own_picture_btn.setFont(font)
        self.open_own_picture_btn.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    font-size:25px;\n"
"\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(223, 41, 53);\n"
"    color: white;\n"
"}")
        self.open_own_picture_btn.setObjectName("open_own_picture_btn")
        self.open_recent_list_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_recent_list_btn.setGeometry(QtCore.QRect(250, 390, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Inter,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.open_recent_list_btn.setFont(font)
        self.open_recent_list_btn.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    font-size:25px;\n"
"\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(223, 41, 53);\n"
"    color: white;\n"
"}")
        self.open_recent_list_btn.setObjectName("open_recent_list_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Создавалка мемов"))
        self.open_shablon_list_btn.setText(_translate("MainWindow", "По шаблону"))
        self.open_own_picture_btn.setText(_translate("MainWindow", "Своя картинка"))
        self.open_recent_list_btn.setText(_translate("MainWindow", "Недавние"))
