# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\recent_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1100, 400)
        self.list = QtWidgets.QListWidget(Form)
        self.list.setGeometry(QtCore.QRect(50, 50, 1000, 300))
        self.list.setMinimumSize(QtCore.QSize(0, 0))
        self.list.setStyleSheet("QListWidget::item {\n"
"margin-right: 50px;\n"
"\n"
"}\n"
"QListWidget{\n"
"border: none;\n"
"font-family: Inter,sans-serif;\n"
"font-weight: 500;\n"
"font-size:15px;\n"
"}")
        self.list.setLineWidth(1)
        self.list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.list.setAutoScroll(True)
        self.list.setAutoScrollMargin(16)
        self.list.setAlternatingRowColors(False)
        self.list.setIconSize(QtCore.QSize(200, 200))
        self.list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.list.setProperty("isWrapping", False)
        self.list.setResizeMode(QtWidgets.QListView.Fixed)
        self.list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.list.setViewMode(QtWidgets.QListView.IconMode)
        self.list.setUniformItemSizes(False)
        self.list.setBatchSize(100)
        self.list.setSelectionRectVisible(True)
        self.list.setObjectName("list")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
