# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\shablon_list.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(981, 287)
        Form.setStyleSheet("background-color: rgb(230, 232, 230);\n"
"")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 10, 161, 51))
        self.label.setStyleSheet("font-family: Inter,sans-serif;\n"
"font-weight: 500;\n"
"font-size:20px;\n"
"")
        self.label.setObjectName("label")
        self.search_edit = QtWidgets.QLineEdit(Form)
        self.search_edit.setGeometry(QtCore.QRect(180, 10, 801, 50))
        self.search_edit.setStyleSheet("border-radius: 20px;\n"
"background-color: white;")
        self.search_edit.setObjectName("search_edit")
        self.list = QtWidgets.QListWidget(Form)
        self.list.setGeometry(QtCore.QRect(10, 70, 961, 211))
        self.list.setMinimumSize(QtCore.QSize(0, 0))
        self.list.setStyleSheet("QListWidget::item {\n"
"margin-right: 50px;\n"
"\n"
"}\n"
"QListWidget{\n"
"border: none;\n"
"font-family: Inter,sans-serif;\n"
"font-weight: 500;\n"
"font-size:15px;\n"
"}")
        self.list.setLineWidth(1)
        self.list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.list.setAutoScroll(True)
        self.list.setAutoScrollMargin(16)
        self.list.setAlternatingRowColors(False)
        self.list.setIconSize(QtCore.QSize(100, 100))
        self.list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.list.setProperty("isWrapping", False)
        self.list.setResizeMode(QtWidgets.QListView.Fixed)
        self.list.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.list.setViewMode(QtWidgets.QListView.IconMode)
        self.list.setUniformItemSizes(False)
        self.list.setBatchSize(100)
        self.list.setSelectionRectVisible(True)
        self.list.setObjectName("list")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Поиск шаблона"))
