# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI\text_parametrs_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(460, 400)
        Form.setStyleSheet("background-color: rgb(230, 232, 230);")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 461, 381))
        self.tabWidget.setStyleSheet("background-color: rgb(230, 232, 230);")
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.change_color = QtWidgets.QPushButton(self.tab)
        self.change_color.setGeometry(QtCore.QRect(20, 100, 411, 70))
        self.change_color.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-radius: 10px;\n"
"\n"
"")
        self.change_color.setText("")
        self.change_color.setObjectName("change_color")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 260, 121, 51))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.change_x = QtWidgets.QSpinBox(self.horizontalLayoutWidget_3)
        self.change_x.setStyleSheet("")
        self.change_x.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.change_x.setPrefix("")
        self.change_x.setMaximum(500)
        self.change_x.setObjectName("change_x")
        self.horizontalLayout_5.addWidget(self.change_x)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(40, 30, 411, 51))
        font = QtGui.QFont()
        font.setFamily("Inter,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("font-size:20px;\n"
"\n"
"font-family: Inter,sans-serif;\n"
"font-weight: 500;\n"
"border-radius: 10px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(310, 260, 121, 51))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.change_y = QtWidgets.QSpinBox(self.horizontalLayoutWidget_2)
        self.change_y.setButtonSymbols(QtWidgets.QAbstractSpinBox.UpDownArrows)
        self.change_y.setPrefix("")
        self.change_y.setMaximum(500)
        self.change_y.setObjectName("change_y")
        self.horizontalLayout_4.addWidget(self.change_y)
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setGeometry(QtCore.QRect(69, 210, 361, 30))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(20, 210, 41, 30))
        self.label_3.setObjectName("label_3")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(150, 210, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Inter,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.label.setFont(font)
        self.label.setStyleSheet("font-family: Inter,sans-serif;\n"
"font-weight: 500;\n"
"font-size:20px;\n"
"")
        self.label.setObjectName("label")
        self.font_size_box = QtWidgets.QSpinBox(self.tab_2)
        self.font_size_box.setGeometry(QtCore.QRect(130, 250, 201, 41))
        self.font_size_box.setProperty("value", 20)
        self.font_size_box.setObjectName("font_size_box")
        self.select_self_font_btn = QtWidgets.QPushButton(self.tab_2)
        self.select_self_font_btn.setGeometry(QtCore.QRect(80, 130, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Inter,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.select_self_font_btn.setFont(font)
        self.select_self_font_btn.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    font-size:20px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(223, 41, 53);\n"
"    color: white;\n"
"}")
        self.select_self_font_btn.setObjectName("select_self_font_btn")
        self.select_own_font_btn = QtWidgets.QPushButton(self.tab_2)
        self.select_own_font_btn.setGeometry(QtCore.QRect(80, 40, 300, 70))
        font = QtGui.QFont()
        font.setFamily("Inter,sans-serif")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.select_own_font_btn.setFont(font)
        self.select_own_font_btn.setStyleSheet("QPushButton\n"
"{\n"
"    font-family: Inter,sans-serif;\n"
"    background-color: rgb(233, 196, 106);\n"
"    font-weight: 500;\n"
"    font-size:20px;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(223, 41, 53);\n"
"    color: white;\n"
"}")
        self.select_own_font_btn.setObjectName("select_own_font_btn")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "х"))
        self.change_x.setSuffix(_translate("Form", "px"))
        self.label_2.setText(_translate("Form", "Кликните по полю ниже, чтобы выбрать \n"
"цвет шрифта"))
        self.label_5.setText(_translate("Form", "y"))
        self.change_y.setSuffix(_translate("Form", "px"))
        self.label_3.setText(_translate("Form", "Текст:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Вид шрифта"))
        self.label.setText(_translate("Form", "Размер шрифта"))
        self.font_size_box.setSuffix(_translate("Form", "px"))
        self.select_self_font_btn.setText(_translate("Form", "Выбрать начертание шрифта\n"
"из встроенных"))
        self.select_own_font_btn.setText(_translate("Form", "Своё начертание \n"
" шрифта"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Начертание шрифта"))
